export const services = [
  {
    id: 1,
    icon: "🧹",
    title: "Ménage à domicile",
    description: "Nettoyage complet de votre intérieur par des professionnels de confiance.",
    slug: "menage",
  },
  {
    id: 2,
    icon: "🛋️",
    title: "Nettoyage canapé",
    description: "Remise à neuf de vos canapés et fauteuils avec du matériel professionnel.",
    slug: "nettoyage-canape",
  },
  {
    id: 3,
    icon: "🧪",
    title: "Désinfection",
    description: "Désinfection complète de vos espaces de vie pour un environnement sain.",
    slug: "desinfection",
  },
  {
    id: 4,
    icon: "👔",
    title: "Repassage",
    description: "Service de repassage à domicile rapide et soigné pour votre linge.",
    slug: "repassage",
  },
  {
    id: 5,
    icon: "👶",
    title: "Babysitting",
    description: "Garde d'enfants par des personnes qualifiées et de confiance.",
    slug: "babysitting",
  },
  {
    id: 6,
    icon: "💻",
    title: "Aide informatique",
    description: "Dépannage, installation et assistance informatique à votre domicile.",
    slug: "aide-informatique",
  },
  {
    id: 7,
    icon: "✂️",
    title: "Coiffure à domicile",
    description: "Coiffeurs professionnels qui se déplacent chez vous pour vos soins.",
    slug: "coiffure",
  },
  {
    id: 8,
    icon: "🔧",
    title: "Petits dépannages",
    description: "Réparations courantes, montage de meubles, fixations et petits travaux.",
    slug: "depannage",
  },
];

export const providers = [
  {
    id: 1,
    name: "Sophie Martin",
    service: "Ménage à domicile",
    slug: "menage",
    city: "Paris",
    rating: 4.9,
    reviews: 87,
    price: "18€/h",
    available: true,
    avatar: "SM",
    color: "#4A90D9",
    description:
      "Je suis spécialisée dans le ménage à domicile depuis plus de 6 ans. Ponctuelle, soigneuse et discrète, j'apporte avec moi tout le matériel nécessaire. Ma priorité est votre satisfaction.",
    skills: ["Nettoyage complet", "Cuisine & salle de bain", "Vitres", "Rangement"],
    schedule: ["Lundi 8h-18h", "Mercredi 8h-18h", "Vendredi 8h-14h", "Samedi 9h-12h"],
    testimonials: [
      { author: "Marie D.", note: 5, text: "Sophie est fantastique, ma maison n'a jamais été aussi propre !" },
      { author: "Pierre L.", note: 5, text: "Très professionnelle, ponctuelle et agréable. Je la recommande vivement." },
      { author: "Claire B.", note: 4, text: "Excellent travail, très satisfaite de la prestation." },
    ],
  },
  {
    id: 2,
    name: "Karim Benali",
    service: "Aide informatique",
    slug: "aide-informatique",
    city: "Lyon",
    rating: 4.8,
    reviews: 54,
    price: "25€/h",
    available: true,
    avatar: "KB",
    color: "#2ECC71",
    description:
      "Technicien informatique avec 8 ans d'expérience. Je vous aide à résoudre tous vos problèmes : virus, lenteur, installation de logiciels, configuration réseau. Pédagogue et patient.",
    skills: ["Dépannage PC & Mac", "Virus & sécurité", "Réseau & Wi-Fi", "Formation seniors"],
    schedule: ["Lundi 9h-19h", "Mardi 9h-19h", "Jeudi 9h-19h", "Samedi 10h-16h"],
    testimonials: [
      { author: "Jacqueline M.", note: 5, text: "Très patient avec moi, il a tout expliqué clairement. Problème résolu en 30 minutes !" },
      { author: "Thomas R.", note: 5, text: "Compétent et efficace. Mon ordinateur fonctionne comme neuf." },
      { author: "Nathalie S.", note: 4, text: "Bon service, rapide et honnête sur le tarif." },
    ],
  },
  {
    id: 3,
    name: "Amina Coulibaly",
    service: "Babysitting",
    slug: "babysitting",
    city: "Marseille",
    rating: 4.9,
    reviews: 63,
    price: "12€/h",
    available: false,
    avatar: "AC",
    color: "#E67E22",
    description:
      "Diplômée d'État petite enfance, je garde vos enfants avec bienveillance et professionnalisme depuis 5 ans. Activités, aide aux devoirs, bain et repas inclus selon vos besoins.",
    skills: ["0-12 ans", "Aide aux devoirs", "Activités créatives", "Premiers secours"],
    schedule: ["Lundi 7h-20h", "Mardi 7h-20h", "Mercredi 7h-20h", "Jeudi 7h-20h"],
    testimonials: [
      { author: "Fatou K.", note: 5, text: "Mes enfants adorent Amina ! Elle est douce, créative et très impliquée." },
      { author: "Antoine P.", note: 5, text: "Sérieuse et fiable, nous lui faisons entièrement confiance." },
    ],
  },
  {
    id: 4,
    name: "Lucas Bernard",
    service: "Petits dépannages",
    slug: "depannage",
    city: "Paris",
    rating: 4.7,
    reviews: 41,
    price: "30€/h",
    available: true,
    avatar: "LB",
    color: "#9B59B6",
    description:
      "Handyman expérimenté, je prends en charge tous vos petits travaux : montage de meubles IKEA, installation d'étagères, réparations diverses. Rapide, propre et efficace.",
    skills: ["Montage meubles", "Fixation & accrochage", "Plomberie légère", "Peinture"],
    schedule: ["Mercredi 8h-18h", "Vendredi 8h-18h", "Samedi 8h-17h", "Dimanche 9h-14h"],
    testimonials: [
      { author: "Emma T.", note: 5, text: "Lucas a monté 3 meubles en moins de 2h, impeccable !" },
      { author: "Julien F.", note: 4, text: "Travail soigné, je referai appel à lui sans hésiter." },
    ],
  },
  {
    id: 5,
    name: "Yasmine Diallo",
    service: "Coiffure à domicile",
    slug: "coiffure",
    city: "Bordeaux",
    rating: 4.8,
    reviews: 72,
    price: "35€/prestation",
    available: true,
    avatar: "YD",
    color: "#E91E8C",
    description:
      "Coiffeuse diplômée avec 7 ans d'expérience en salon et à domicile. Coupes, colorations, soins, coiffures afro et européennes. Je me déplace avec tout mon matériel professionnel.",
    skills: ["Coupe femme & homme", "Coloration", "Soins capillaires", "Coiffures afro"],
    schedule: ["Mardi 9h-19h", "Jeudi 9h-19h", "Vendredi 9h-19h", "Samedi 8h-17h"],
    testimonials: [
      { author: "Léa M.", note: 5, text: "Yasmine est talentueuse et très à l'écoute. Je ne vais plus en salon !" },
      { author: "Sandra K.", note: 5, text: "Résultat magnifique, elle prend le temps de bien faire les choses." },
    ],
  },
  {
    id: 6,
    name: "Philippe Moreau",
    service: "Nettoyage canapé",
    slug: "nettoyage-canape",
    city: "Nantes",
    rating: 4.6,
    reviews: 38,
    price: "80€/canapé",
    available: true,
    avatar: "PM",
    color: "#00BCD4",
    description:
      "Spécialiste du nettoyage en profondeur de canapés, fauteuils et matelas. Utilisation de produits écologiques et de machines professionnelles pour un résultat impeccable.",
    skills: ["Canapés tissu & cuir", "Fauteuils", "Matelas", "Tapis"],
    schedule: ["Lundi 8h-17h", "Mercredi 8h-17h", "Vendredi 8h-17h"],
    testimonials: [
      { author: "Isabelle C.", note: 5, text: "Mon canapé blanc est comme neuf ! Travail remarquable." },
      { author: "Marc D.", note: 4, text: "Très bon nettoyage, je recommande." },
    ],
  },
];

export const cities = ["Toutes les villes", "Paris", "Lyon", "Marseille", "Bordeaux", "Nantes", "Toulouse", "Nice", "Strasbourg"];

export const servicesList = ["Tous les services", "Ménage à domicile", "Nettoyage canapé", "Désinfection", "Repassage", "Babysitting", "Aide informatique", "Coiffure à domicile", "Petits dépannages"];

export const testimonials = [
  {
    name: "Marie Dupont",
    city: "Paris",
    avatar: "MD",
    color: "#4A90D9",
    note: 5,
    text: "Prestalya m'a permis de trouver une femme de ménage de confiance en quelques minutes. Le service est simple, rapide et les prestataires sont vraiment professionnels.",
  },
  {
    name: "Jean-Pierre Fontaine",
    city: "Lyon",
    avatar: "JF",
    color: "#2ECC71",
    note: 5,
    text: "J'avais besoin d'aide urgente pour mon ordinateur. En 1h, un technicien était chez moi. Excellent service, je recommande à tous.",
  },
  {
    name: "Stéphanie Moreau",
    city: "Bordeaux",
    avatar: "SM",
    color: "#E67E22",
    note: 5,
    text: "La coiffeuse est venue directement à domicile, c'était un vrai confort. Résultat parfait et prix très raisonnable.",
  },
];
