export const services = [
  // Maison
  { id: 1, category: "Maison", shortLabel: "Ménage", title: "Ménage à domicile", description: "Nettoyage complet de votre intérieur par des professionnels de confiance.", slug: "menage", photo: "https://images.unsplash.com/photo-1581578731548-c64695cc6952?auto=format&fit=crop&w=600&h=380&q=80" },
  { id: 2, category: "Maison", shortLabel: "Nett. canapé", title: "Nettoyage canapé", description: "Remise à neuf de vos canapés et fauteuils avec du matériel professionnel.", slug: "nettoyage-canape", photo: "https://images.unsplash.com/photo-1555041469-a586c61ea9bc?auto=format&fit=crop&w=600&h=380&q=80" },
  { id: 3, category: "Maison", shortLabel: "Désinfection", title: "Désinfection", description: "Désinfection complète de vos espaces pour un environnement sain.", slug: "desinfection", photo: "https://images.unsplash.com/photo-1584820927498-cfe5211fd8bf?auto=format&fit=crop&w=600&h=380&q=80" },
  { id: 4, category: "Maison", shortLabel: "Repassage", title: "Repassage", description: "Service de repassage à domicile rapide et soigné pour votre linge.", slug: "repassage", photo: "https://images.unsplash.com/photo-1517677208171-0bc6725a3e60?auto=format&fit=crop&w=600&h=380&q=80" },
  { id: 5, category: "Maison", shortLabel: "Babysitting", title: "Babysitting", description: "Garde d'enfants par des personnes qualifiées et de confiance.", slug: "babysitting", photo: "https://images.unsplash.com/photo-1503454537195-1dcabb73ffb9?auto=format&fit=crop&w=600&h=380&q=80" },
  { id: 6, category: "Maison", shortLabel: "Informatique", title: "Aide informatique", description: "Dépannage, installation et assistance informatique à domicile.", slug: "aide-informatique", photo: "https://images.unsplash.com/photo-1517694712202-14dd9538aa97?auto=format&fit=crop&w=600&h=380&q=80" },
  { id: 7, category: "Maison", shortLabel: "Dépannages", title: "Petits dépannages", description: "Réparations courantes, montage de meubles et petits travaux.", slug: "depannage", photo: "https://images.unsplash.com/photo-1504148455328-c376907d081c?auto=format&fit=crop&w=600&h=380&q=80" },
  { id: 14, category: "Maison", shortLabel: "Désinsectisation", title: "Désinsectisation", description: "Élimination des insectes nuisibles (cafards, punaises, fourmis, moustiques) par des professionnels certifiés.", slug: "desinsectisation", photo: "/images/desinsectisation.jpg" },
  { id: 15, category: "Maison", shortLabel: "Dératisation", title: "Dératisation", description: "Traitement anti-rongeurs (rats, souris) rapide et efficace avec des produits homologués.", slug: "deratisation", photo: "/images/deratisation.jpg" },
  // Artisan
  { id: 8, category: "Artisan", shortLabel: "Électricité", title: "Électricité", description: "Installations, dépannages et mises aux normes électriques par des électriciens certifiés.", slug: "electricite", photo: "https://images.unsplash.com/photo-1621905251189-08b45d6a269e?auto=format&fit=crop&w=600&h=380&q=80" },
  { id: 9, category: "Artisan", shortLabel: "Plomberie", title: "Plomberie", description: "Fuites, installations sanitaires, chauffe-eau : vos plombiers interviennent rapidement.", slug: "plomberie", photo: "https://images.unsplash.com/photo-1585704032915-c3400ca199e7?auto=format&fit=crop&w=600&h=380&q=80" },
  { id: 10, category: "Artisan", shortLabel: "Menuiserie", title: "Menuiserie", description: "Pose de portes, fenêtres, parquet et aménagements sur mesure par des menuisiers qualifiés.", slug: "menuiserie", photo: "https://images.unsplash.com/photo-1601058268499-e52658b8bb88?auto=format&fit=crop&w=600&h=380&q=80" },
  // Beauté
  { id: 11, category: "Beauté", shortLabel: "Coiffure", title: "Coiffure à domicile", description: "Coiffeurs professionnels qui se déplacent chez vous pour vos soins capillaires.", slug: "coiffure", photo: "https://images.unsplash.com/photo-1560869713-7d0a29430803?auto=format&fit=crop&w=600&h=380&q=80" },
  { id: 12, category: "Beauté", shortLabel: "Maquillage", title: "Maquillage", description: "Maquilleuses professionnelles pour vos événements, mariages ou séances photo à domicile.", slug: "maquillage", photo: "https://images.unsplash.com/photo-1487412947147-5cebf100ffc2?auto=format&fit=crop&w=600&h=380&q=80" },
  { id: 13, category: "Beauté", shortLabel: "Onglerie", title: "Onglerie", description: "Pose de gel, vernis semi-permanent, nail art et soins des ongles à domicile.", slug: "onglerie", photo: "https://images.unsplash.com/photo-1604654894610-df63bc536371?auto=format&fit=crop&w=600&h=380&q=80" },
];

export const providers = [
  {
    id: 1, name: "Sophie Martin", service: "Ménage à domicile", slug: "menage", city: "Paris", district: "15e arrondissement",
    rating: 4.9, reviews: 128, price: "à partir de 18€/h", available: true, avatar: "SM", color: "#4A90D9",
    photo: "https://images.unsplash.com/photo-1494790108377-be9c29b29330?auto=format&fit=crop&w=120&h=120&q=80",
    description: "Spécialisée dans le ménage à domicile depuis plus de 6 ans. Ponctuelle, soigneuse et discrète, j'apporte tout le matériel nécessaire.",
    qualities: ["Réponse rapide", "Travail soigné", "Clients satisfaits"],
    skills: ["Nettoyage complet", "Cuisine & salle de bain", "Vitres", "Rangement"],
    tarifs: [{ label: "Ménage classique", price: "à partir de 18€/h" }, { label: "Grand ménage", price: "à partir de 28€/h" }, { label: "Repassage", price: "à partir de 15€/h" }],
    schedule: { Lun: ["08h-12h", "14h-18h"], Mar: ["08h-12h"], Mer: ["08h-12h", "14h-18h"], Jeu: [], Ven: ["08h-12h"], Sam: ["09h-12h"], Dim: [] },
    testimonials: [{ author: "Marie D.", note: 5, text: "Sophie est fantastique, ma maison n'a jamais été aussi propre !" }, { author: "Pierre L.", note: 5, text: "Très professionnelle, ponctuelle et agréable. Je la recommande." }, { author: "Claire B.", note: 4, text: "Excellent travail, très satisfaite de la prestation." }],
  },
  {
    id: 2, name: "Karim Benali", service: "Aide informatique", slug: "aide-informatique", city: "Lyon", district: "Part-Dieu",
    rating: 4.8, reviews: 54, price: "à partir de 25€/h", available: true, avatar: "KB", color: "#2ECC71",
    photo: "https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?auto=format&fit=crop&w=120&h=120&q=80",
    description: "Technicien informatique avec 8 ans d'expérience. Je résous tous vos problèmes : virus, lenteur, installation, réseau.",
    qualities: ["Réponse rapide", "Expert certifié", "Pédagogue"],
    skills: ["Dépannage PC & Mac", "Virus & sécurité", "Réseau & Wi-Fi", "Formation seniors"],
    tarifs: [{ label: "Dépannage standard", price: "à partir de 25€/h" }, { label: "Installation logiciels", price: "à partir de 30€" }, { label: "Configuration réseau", price: "à partir de 40€" }],
    schedule: { Lun: ["09h-12h", "14h-19h"], Mar: ["09h-19h"], Mer: [], Jeu: ["09h-19h"], Ven: ["09h-17h"], Sam: ["10h-16h"], Dim: [] },
    testimonials: [{ author: "Jacqueline M.", note: 5, text: "Très patient, tout expliqué clairement. Problème résolu en 30 minutes !" }, { author: "Thomas R.", note: 5, text: "Compétent et efficace. Mon ordinateur fonctionne comme neuf." }],
  },
  {
    id: 3, name: "Amina Coulibaly", service: "Babysitting", slug: "babysitting", city: "Marseille", district: "Vieux-Port",
    rating: 4.9, reviews: 63, price: "à partir de 12€/h", available: false, avatar: "AC", color: "#E67E22",
    photo: "https://images.unsplash.com/photo-1531123897727-8f129e1688ce?auto=format&fit=crop&w=120&h=120&q=80",
    description: "Diplômée petite enfance, je garde vos enfants avec bienveillance depuis 5 ans. Activités, aide aux devoirs, bain et repas inclus.",
    qualities: ["Diplômée d'État", "Expérience 5 ans", "Premiers secours"],
    skills: ["0-12 ans", "Aide aux devoirs", "Activités créatives", "Premiers secours"],
    tarifs: [{ label: "Garde ponctuelle", price: "à partir de 12€/h" }, { label: "Garde régulière", price: "à partir de 10€/h" }, { label: "Nuit complète", price: "à partir de 60€" }],
    schedule: { Lun: ["07h-20h"], Mar: ["07h-20h"], Mer: ["07h-20h"], Jeu: ["07h-20h"], Ven: ["07h-20h"], Sam: [], Dim: [] },
    testimonials: [{ author: "Fatou K.", note: 5, text: "Mes enfants adorent Amina ! Douce, créative et très impliquée." }, { author: "Antoine P.", note: 5, text: "Sérieuse et fiable, nous lui faisons entièrement confiance." }],
  },
  {
    id: 4, name: "Lucas Bernard", service: "Petits dépannages", slug: "depannage", city: "Paris", district: "Montmartre",
    rating: 4.7, reviews: 41, price: "à partir de 30€/h", available: true, avatar: "LB", color: "#9B59B6",
    photo: "https://images.unsplash.com/photo-1500648767791-00dcc994a43e?auto=format&fit=crop&w=120&h=120&q=80",
    description: "Handyman expérimenté, je prends en charge tous vos petits travaux : montage IKEA, étagères, réparations.",
    qualities: ["Rapide & efficace", "Matériel fourni", "Garantie satisfait"],
    skills: ["Montage meubles", "Fixation & accrochage", "Plomberie légère", "Peinture"],
    tarifs: [{ label: "Montage meubles", price: "à partir de 30€/h" }, { label: "Petite plomberie", price: "à partir de 40€" }, { label: "Peinture", price: "Devis gratuit" }],
    schedule: { Lun: [], Mar: [], Mer: ["08h-18h"], Jeu: [], Ven: ["08h-18h"], Sam: ["08h-17h"], Dim: ["09h-14h"] },
    testimonials: [{ author: "Emma T.", note: 5, text: "Lucas a monté 3 meubles en moins de 2h, impeccable !" }, { author: "Julien F.", note: 4, text: "Travail soigné, je referai appel à lui sans hésiter." }],
  },
  {
    id: 5, name: "Yasmine Diallo", service: "Coiffure à domicile", slug: "coiffure", city: "Bordeaux", district: "Chartrons",
    rating: 4.8, reviews: 72, price: "à partir de 35€", available: true, avatar: "YD", color: "#E91E8C",
    photo: "https://images.unsplash.com/photo-1544005313-94ddf0286df2?auto=format&fit=crop&w=120&h=120&q=80",
    description: "Coiffeuse diplômée avec 7 ans d'expérience. Coupes, colorations, soins, coiffures afro et européennes.",
    qualities: ["Diplômée", "7 ans d'expérience", "Matériel pro"],
    skills: ["Coupe femme & homme", "Coloration", "Soins capillaires", "Coiffures afro"],
    tarifs: [{ label: "Coupe femme", price: "à partir de 35€" }, { label: "Coloration", price: "à partir de 60€" }, { label: "Soins", price: "à partir de 25€" }],
    schedule: { Lun: [], Mar: ["09h-19h"], Mer: [], Jeu: ["09h-19h"], Ven: ["09h-19h"], Sam: ["08h-17h"], Dim: [] },
    testimonials: [{ author: "Léa M.", note: 5, text: "Yasmine est talentueuse et très à l'écoute. Je ne vais plus en salon !" }, { author: "Sandra K.", note: 5, text: "Résultat magnifique, elle prend le temps de bien faire les choses." }],
  },
  {
    id: 6, name: "Philippe Moreau", service: "Nettoyage canapé", slug: "nettoyage-canape", city: "Nantes", district: "Centre-ville",
    rating: 4.6, reviews: 38, price: "à partir de 80€", available: true, avatar: "PM", color: "#00BCD4",
    photo: "https://images.unsplash.com/photo-1472099645785-5658abf4ff4e?auto=format&fit=crop&w=120&h=120&q=80",
    description: "Spécialiste du nettoyage de canapés, fauteuils et matelas. Produits écologiques et machines professionnelles.",
    qualities: ["Produits écologiques", "Résultat garanti", "Devis gratuit"],
    skills: ["Canapés tissu & cuir", "Fauteuils", "Matelas", "Tapis"],
    tarifs: [{ label: "Canapé 2 places", price: "à partir de 60€" }, { label: "Canapé 3 places", price: "à partir de 80€" }, { label: "Fauteuil", price: "à partir de 35€" }],
    schedule: { Lun: ["08h-17h"], Mar: [], Mer: ["08h-17h"], Jeu: [], Ven: ["08h-17h"], Sam: [], Dim: [] },
    testimonials: [{ author: "Isabelle C.", note: 5, text: "Mon canapé blanc est comme neuf ! Travail remarquable." }, { author: "Marc D.", note: 4, text: "Très bon nettoyage, je recommande." }],
  },
  {
    id: 7, name: "Thierry Dupont", service: "Électricité", slug: "electricite", city: "Paris", district: "11e arrondissement",
    rating: 4.8, reviews: 89, price: "à partir de 60€", available: true, avatar: "TD", color: "#F39C12",
    photo: "https://images.unsplash.com/photo-1558618666-fcd25c85cd64?auto=format&fit=crop&w=120&h=120&q=80",
    description: "Électricien certifié avec 12 ans d'expérience. Dépannage, mise aux normes, installation de prises et luminaires.",
    qualities: ["Certifié Qualifelec", "Devis gratuit", "Urgences 7j/7"],
    skills: ["Dépannage électrique", "Mise aux normes", "Pose luminaires", "Tableau électrique"],
    tarifs: [{ label: "Dépannage urgent", price: "à partir de 60€" }, { label: "Installation prise", price: "à partir de 45€" }, { label: "Mise aux normes", price: "Devis gratuit" }],
    schedule: { Lun: ["08h-18h"], Mar: ["08h-18h"], Mer: ["08h-18h"], Jeu: ["08h-18h"], Ven: ["08h-18h"], Sam: ["09h-14h"], Dim: [] },
    testimonials: [{ author: "Bruno S.", note: 5, text: "Intervention rapide et propre. Thierry est très professionnel." }, { author: "Nathalie V.", note: 5, text: "Excellent travail pour la mise aux normes de notre appartement." }],
  },
  {
    id: 8, name: "Hassan Rami", service: "Plomberie", slug: "plomberie", city: "Lyon", district: "Confluence",
    rating: 4.7, reviews: 64, price: "à partir de 55€", available: true, avatar: "HR", color: "#3498DB",
    photo: "https://images.unsplash.com/photo-1566753323558-f4e0952af115?auto=format&fit=crop&w=120&h=120&q=80",
    description: "Plombier expérimenté, j'interviens rapidement pour toutes fuites, installations sanitaires et chauffe-eau.",
    qualities: ["Réponse en 2h", "Garantie 1 an", "Sans surprise"],
    skills: ["Fuite & dépannage", "Remplacement chauffe-eau", "Salle de bain", "Robinetterie"],
    tarifs: [{ label: "Recherche de fuite", price: "à partir de 55€" }, { label: "Remplacement robinet", price: "à partir de 70€" }, { label: "Installation chauffe-eau", price: "Devis gratuit" }],
    schedule: { Lun: ["07h-19h"], Mar: ["07h-19h"], Mer: ["07h-19h"], Jeu: ["07h-19h"], Ven: ["07h-19h"], Sam: ["08h-16h"], Dim: [] },
    testimonials: [{ author: "Christophe M.", note: 5, text: "Arrivé en 1h pour une fuite urgente. Impeccable !" }, { author: "Alice P.", note: 4, text: "Travail soigné, tarif transparent. Je recommande." }],
  },
  {
    id: 9, name: "René Lacombe", service: "Menuiserie", slug: "menuiserie", city: "Toulouse", district: "Capitole",
    rating: 4.9, reviews: 47, price: "à partir de 40€/h", available: false, avatar: "RL", color: "#8B4513",
    photo: "https://images.unsplash.com/photo-1504307651254-35680f356dfd?auto=format&fit=crop&w=120&h=120&q=80",
    description: "Menuisier artisan avec 15 ans de métier. Pose de portes, fenêtres, parquet, placards et aménagements sur mesure.",
    qualities: ["Artisan d'État", "Matériaux premium", "Sur mesure"],
    skills: ["Pose de portes", "Parquet & stratifié", "Placards sur mesure", "Fenêtres & volets"],
    tarifs: [{ label: "Pose de porte", price: "à partir de 120€" }, { label: "Parquet (par m²)", price: "à partir de 25€/m²" }, { label: "Placard sur mesure", price: "Devis gratuit" }],
    schedule: { Lun: ["07h-17h"], Mar: ["07h-17h"], Mer: ["07h-17h"], Jeu: ["07h-17h"], Ven: ["07h-17h"], Sam: [], Dim: [] },
    testimonials: [{ author: "Sylvie T.", note: 5, text: "Des placards magnifiques, exactement ce que je voulais. Merci René !" }, { author: "Gérard B.", note: 5, text: "Travail d'artisan, grande qualité. Je le recommande les yeux fermés." }],
  },
  {
    id: 10, name: "Inès Toure", service: "Maquillage", slug: "maquillage", city: "Paris", district: "Marais",
    rating: 4.9, reviews: 93, price: "à partir de 50€", available: true, avatar: "IT", color: "#C0392B",
    photo: "https://images.unsplash.com/photo-1520813792240-56fc4a3765a7?auto=format&fit=crop&w=120&h=120&q=80",
    description: "Maquilleuse professionnelle pour mariages, événements et séances photo. Maquillage longue tenue, tous types de peaux.",
    qualities: ["Certifiée pro", "Tous types de peaux", "Maquillage longue tenue"],
    skills: ["Maquillage mariée", "Maquillage soirée", "Maquillage photo", "Cours de maquillage"],
    tarifs: [{ label: "Maquillage soirée", price: "à partir de 50€" }, { label: "Maquillage mariée", price: "à partir de 120€" }, { label: "Cours particulier", price: "à partir de 80€" }],
    schedule: { Lun: [], Mar: ["10h-20h"], Mer: ["10h-20h"], Jeu: ["10h-20h"], Ven: ["10h-20h"], Sam: ["08h-22h"], Dim: ["09h-18h"] },
    testimonials: [{ author: "Camille R.", note: 5, text: "Inès a sublimé mon maquillage pour mon mariage. Toutes mes invitées ont voulu son contact !" }, { author: "Sarah N.", note: 5, text: "Très à l'écoute et le résultat est bluffant. Je ne ferai plus appel à quelqu'un d'autre." }],
  },
  {
    id: 11, name: "Priya Sharma", service: "Onglerie", slug: "onglerie", city: "Paris", district: "Opéra",
    rating: 4.8, reviews: 115, price: "à partir de 30€", available: true, avatar: "PS", color: "#FF69B4",
    photo: "https://images.unsplash.com/photo-1573496359142-b8d87734a5a2?auto=format&fit=crop&w=120&h=120&q=80",
    description: "Prothésiste ongulaire certifiée. Pose gel, vernis semi-permanent, nail art et soins des ongles directement chez vous.",
    qualities: ["Certifiée", "Produits de qualité", "Nail art créatif"],
    skills: ["Pose gel", "Semi-permanent", "Nail art", "Soins ongles"],
    tarifs: [{ label: "Vernis semi-permanent", price: "à partir de 30€" }, { label: "Pose gel", price: "à partir de 50€" }, { label: "Nail art (par ongle)", price: "à partir de 3€/ongle" }],
    schedule: { Lun: ["10h-19h"], Mar: ["10h-19h"], Mer: ["10h-19h"], Jeu: ["10h-19h"], Ven: ["10h-20h"], Sam: ["09h-20h"], Dim: [] },
    testimonials: [{ author: "Lucie F.", note: 5, text: "Des ongles parfaits, Priya est ultra minutieuse et créative !" }, { author: "Jade M.", note: 5, text: "Je ne me déplace plus dans un salon, c'est tellement pratique et le résultat est top." }],
  },
];

export const cities = ["Toutes les villes", "Paris", "Lyon", "Marseille", "Bordeaux", "Nantes", "Toulouse", "Nice"];

export const servicesList = [
  "Tous les services",
  "Ménage à domicile", "Nettoyage canapé", "Désinfection", "Repassage", "Babysitting", "Aide informatique", "Petits dépannages", "Désinsectisation", "Dératisation",
  "Électricité", "Plomberie", "Menuiserie",
  "Coiffure à domicile", "Maquillage", "Onglerie",
];

export const testimonials = [
  { name: "Marie Dupont", city: "Paris", avatar: "MD", color: "#4A90D9", note: 5, text: "Prestalya m'a permis de trouver une femme de ménage de confiance en quelques minutes. Simple, rapide et les prestataires sont vraiment professionnels." },
  { name: "Jean-Pierre Fontaine", city: "Lyon", avatar: "JF", color: "#2ECC71", note: 5, text: "J'avais besoin d'aide urgente pour mon ordinateur. En 1h, un technicien était chez moi. Excellent service, je recommande à tous." },
  { name: "Stéphanie Moreau", city: "Bordeaux", avatar: "SM", color: "#E67E22", note: 5, text: "La coiffeuse est venue directement à domicile. Résultat parfait et prix très raisonnable. Je ne reprendrai plus rendez-vous en salon !" },
];

export const weekDays = ["Lun", "Mar", "Mer", "Jeu", "Ven", "Sam", "Dim"];

export const serviceCategories = [
  { key: "Maison", label: "Maison & Entretien", icon: "🏠", color: "#4A90D9" },
  { key: "Artisan", label: "Artisans", icon: "🔧", color: "#E67E22" },
  { key: "Beauté", label: "Beauté & Bien-être", icon: "✨", color: "#E91E8C" },
];
