export const services = [
  { id: 1, title: "Ménage à domicile", description: "Nettoyage complet de votre intérieur par des professionnels de confiance.", slug: "menage" },
  { id: 2, title: "Nettoyage canapé", description: "Remise à neuf de vos canapés et fauteuils avec du matériel professionnel.", slug: "nettoyage-canape" },
  { id: 3, title: "Désinfection", description: "Désinfection complète de vos espaces pour un environnement sain.", slug: "desinfection" },
  { id: 4, title: "Repassage", description: "Service de repassage à domicile rapide et soigné pour votre linge.", slug: "repassage" },
  { id: 5, title: "Babysitting", description: "Garde d'enfants par des personnes qualifiées et de confiance.", slug: "babysitting" },
  { id: 6, title: "Aide informatique", description: "Dépannage, installation et assistance informatique à domicile.", slug: "aide-informatique" },
  { id: 7, title: "Coiffure à domicile", description: "Coiffeurs professionnels qui se déplacent chez vous pour vos soins.", slug: "coiffure" },
  { id: 8, title: "Petits dépannages", description: "Réparations courantes, montage de meubles et petits travaux.", slug: "depannage" },
];

export const providers = [
  {
    id: 1,
    name: "Sophie Martin",
    service: "Ménage à domicile",
    slug: "menage",
    city: "Paris",
    district: "15e arrondissement",
    rating: 4.9,
    reviews: 128,
    price: "à partir de 18€/h",
    available: true,
    avatar: "SM",
    color: "#4A90D9",
    photo: "https://images.unsplash.com/photo-1494790108377-be9c29b29330?auto=format&fit=crop&w=120&h=120&q=80",
    description: "Spécialisée dans le ménage à domicile depuis plus de 6 ans. Ponctuelle, soigneuse et discrète, j'apporte tout le matériel nécessaire.",
    qualities: ["Réponse rapide", "Travail soigné", "Clients satisfaits"],
    skills: ["Nettoyage complet", "Cuisine & salle de bain", "Vitres", "Rangement"],
    tarifs: [
      { label: "Ménage classique", price: "À partir de 18€/h" },
      { label: "Grand ménage", price: "À partir de 28€/h" },
      { label: "Repassage", price: "À partir de 15€/h" },
    ],
    schedule: { Lun: ["08h–12h", "14h–18h"], Mar: ["08h–12h"], Mer: ["08h–12h", "14h–18h"], Jeu: [], Ven: ["08h–12h"], Sam: ["09h–12h"], Dim: [] },
    testimonials: [
      { author: "Marie D.", note: 5, text: "Sophie est fantastique, ma maison n'a jamais été aussi propre !" },
      { author: "Pierre L.", note: 5, text: "Très professionnelle, ponctuelle et agréable. Je la recommande." },
      { author: "Claire B.", note: 4, text: "Excellent travail, très satisfaite de la prestation." },
    ],
  },
  {
    id: 2,
    name: "Karim Benali",
    service: "Aide informatique",
    slug: "aide-informatique",
    city: "Lyon",
    district: "Part-Dieu",
    rating: 4.8,
    reviews: 54,
    price: "à partir de 25€/h",
    available: true,
    avatar: "KB",
    color: "#2ECC71",
    photo: "https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?auto=format&fit=crop&w=120&h=120&q=80",
    description: "Technicien informatique avec 8 ans d'expérience. Je résous tous vos problèmes : virus, lenteur, installation, réseau.",
    qualities: ["Réponse rapide", "Expert certifié", "Pédagogue"],
    skills: ["Dépannage PC & Mac", "Virus & sécurité", "Réseau & Wi-Fi", "Formation seniors"],
    tarifs: [
      { label: "Dépannage standard", price: "À partir de 25€/h" },
      { label: "Installation logiciels", price: "À partir de 30€" },
      { label: "Configuration réseau", price: "À partir de 40€" },
    ],
    schedule: { Lun: ["09h–12h", "14h–19h"], Mar: ["09h–19h"], Mer: [], Jeu: ["09h–19h"], Ven: ["09h–17h"], Sam: ["10h–16h"], Dim: [] },
    testimonials: [
      { author: "Jacqueline M.", note: 5, text: "Très patient, tout expliqué clairement. Problème résolu en 30 minutes !" },
      { author: "Thomas R.", note: 5, text: "Compétent et efficace. Mon ordinateur fonctionne comme neuf." },
    ],
  },
  {
    id: 3,
    name: "Amina Coulibaly",
    service: "Babysitting",
    slug: "babysitting",
    city: "Marseille",
    district: "Vieux-Port",
    rating: 4.9,
    reviews: 63,
    price: "à partir de 12€/h",
    available: false,
    avatar: "AC",
    color: "#E67E22",
    photo: "https://images.unsplash.com/photo-1531123897727-8f129e1688ce?auto=format&fit=crop&w=120&h=120&q=80",
    description: "Diplômée petite enfance, je garde vos enfants avec bienveillance depuis 5 ans. Activités, aide aux devoirs, bain et repas inclus.",
    qualities: ["Diplômée d'État", "Expérience 5 ans", "Premiers secours"],
    skills: ["0–12 ans", "Aide aux devoirs", "Activités créatives", "Premiers secours"],
    tarifs: [
      { label: "Garde ponctuelle", price: "À partir de 12€/h" },
      { label: "Garde régulière", price: "À partir de 10€/h" },
      { label: "Nuit complète", price: "À partir de 60€" },
    ],
    schedule: { Lun: ["07h–20h"], Mar: ["07h–20h"], Mer: ["07h–20h"], Jeu: ["07h–20h"], Ven: ["07h–20h"], Sam: [], Dim: [] },
    testimonials: [
      { author: "Fatou K.", note: 5, text: "Mes enfants adorent Amina ! Douce, créative et très impliquée." },
      { author: "Antoine P.", note: 5, text: "Sérieuse et fiable, nous lui faisons entièrement confiance." },
    ],
  },
  {
    id: 4,
    name: "Lucas Bernard",
    service: "Petits dépannages",
    slug: "depannage",
    city: "Paris",
    district: "Montmartre",
    rating: 4.7,
    reviews: 41,
    price: "à partir de 30€/h",
    available: true,
    avatar: "LB",
    color: "#9B59B6",
    photo: "https://images.unsplash.com/photo-1500648767791-00dcc994a43e?auto=format&fit=crop&w=120&h=120&q=80",
    description: "Handyman expérimenté, je prends en charge tous vos petits travaux : montage IKEA, étagères, réparations.",
    qualities: ["Rapide & efficace", "Matériel fourni", "Garantie satisfait"],
    skills: ["Montage meubles", "Fixation & accrochage", "Plomberie légère", "Peinture"],
    tarifs: [
      { label: "Montage meubles", price: "À partir de 30€/h" },
      { label: "Petite plomberie", price: "À partir de 40€" },
      { label: "Peinture", price: "Devis gratuit" },
    ],
    schedule: { Lun: [], Mar: [], Mer: ["08h–18h"], Jeu: [], Ven: ["08h–18h"], Sam: ["08h–17h"], Dim: ["09h–14h"] },
    testimonials: [
      { author: "Emma T.", note: 5, text: "Lucas a monté 3 meubles en moins de 2h, impeccable !" },
      { author: "Julien F.", note: 4, text: "Travail soigné, je referai appel à lui sans hésiter." },
    ],
  },
  {
    id: 5,
    name: "Yasmine Diallo",
    service: "Coiffure à domicile",
    slug: "coiffure",
    city: "Bordeaux",
    district: "Chartrons",
    rating: 4.8,
    reviews: 72,
    price: "à partir de 35€",
    available: true,
    avatar: "YD",
    color: "#E91E8C",
    photo: "https://images.unsplash.com/photo-1544005313-94ddf0286df2?auto=format&fit=crop&w=120&h=120&q=80",
    description: "Coiffeuse diplômée avec 7 ans d'expérience. Coupes, colorations, soins, coiffures afro et européennes.",
    qualities: ["Diplômée", "7 ans d'expérience", "Matériel pro"],
    skills: ["Coupe femme & homme", "Coloration", "Soins capillaires", "Coiffures afro"],
    tarifs: [
      { label: "Coupe femme", price: "À partir de 35€" },
      { label: "Coloration", price: "À partir de 60€" },
      { label: "Soins", price: "À partir de 25€" },
    ],
    schedule: { Lun: [], Mar: ["09h–19h"], Mer: [], Jeu: ["09h–19h"], Ven: ["09h–19h"], Sam: ["08h–17h"], Dim: [] },
    testimonials: [
      { author: "Léa M.", note: 5, text: "Yasmine est talentueuse et très à l'écoute. Je ne vais plus en salon !" },
      { author: "Sandra K.", note: 5, text: "Résultat magnifique, elle prend le temps de bien faire les choses." },
    ],
  },
  {
    id: 6,
    name: "Philippe Moreau",
    service: "Nettoyage canapé",
    slug: "nettoyage-canape",
    city: "Nantes",
    district: "Centre-ville",
    rating: 4.6,
    reviews: 38,
    price: "à partir de 80€",
    available: true,
    avatar: "PM",
    color: "#00BCD4",
    photo: "https://images.unsplash.com/photo-1472099645785-5658abf4ff4e?auto=format&fit=crop&w=120&h=120&q=80",
    description: "Spécialiste du nettoyage de canapés, fauteuils et matelas. Produits écologiques et machines professionnelles.",
    qualities: ["Produits écologiques", "Résultat garanti", "Devis gratuit"],
    skills: ["Canapés tissu & cuir", "Fauteuils", "Matelas", "Tapis"],
    tarifs: [
      { label: "Canapé 2 places", price: "À partir de 60€" },
      { label: "Canapé 3 places", price: "À partir de 80€" },
      { label: "Fauteuil", price: "À partir de 35€" },
    ],
    schedule: { Lun: ["08h–17h"], Mar: [], Mer: ["08h–17h"], Jeu: [], Ven: ["08h–17h"], Sam: [], Dim: [] },
    testimonials: [
      { author: "Isabelle C.", note: 5, text: "Mon canapé blanc est comme neuf ! Travail remarquable." },
      { author: "Marc D.", note: 4, text: "Très bon nettoyage, je recommande." },
    ],
  },
];

export const cities = ["Toutes les villes", "Paris", "Lyon", "Marseille", "Bordeaux", "Nantes", "Toulouse", "Nice"];
export const servicesList = ["Tous les services", "Ménage à domicile", "Nettoyage canapé", "Désinfection", "Repassage", "Babysitting", "Aide informatique", "Coiffure à domicile", "Petits dépannages"];

export const testimonials = [
  { name: "Marie Dupont", city: "Paris", avatar: "MD", color: "#4A90D9", note: 5, text: "Prestalya m'a permis de trouver une femme de ménage de confiance en quelques minutes. Simple, rapide et les prestataires sont vraiment professionnels." },
  { name: "Jean-Pierre Fontaine", city: "Lyon", avatar: "JF", color: "#2ECC71", note: 5, text: "J'avais besoin d'aide urgente pour mon ordinateur. En 1h, un technicien était chez moi. Excellent service, je recommande à tous." },
  { name: "Stéphanie Moreau", city: "Bordeaux", avatar: "SM", color: "#E67E22", note: 5, text: "La coiffeuse est venue directement à domicile. Résultat parfait et prix très raisonnable. Je ne reprendrai plus rendez-vous en salon !" },
];

export const weekDays = ["Lun", "Mar", "Mer", "Jeu", "Ven", "Sam", "Dim"];
